cp -rf /mnt/light/DPEmeaRhlog/ignition/configmgr2.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/igchild.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/appdatamgr.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/htmltable.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/formsmanager.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/template/* /ignition/template/
cp -rf /mnt/light/DPEmeaRhlog/ignition/static/* /ignition/static/
cp -rf /mnt/light/DPEmeaRhlog/ignition/html* /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/igchild2.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/makespecial.py /ignition/
cp -rf /mnt/light/DPEmeaRhlog/ignition/chunker.py /ignition/
