FROM debian:jessie

RUN apt-get update \
        && apt-get install --no-install-recommends --no-install-suggests -y \
                python-pip \
                git \
		wget \
        && pip install web.py
ENV SETUP_DIR="ig_setup"
RUN mkdir $SETUP_DIR
WORKDIR $SETUP_DIR

ARG build_time_var="2"
ARG build_time_branch="master"
ENV cur_branch=$branch
ENV SETUP_VER=$build_time_var
RUN wget https://raw.githubusercontent.com/codemation/py-k8s/$cur_branch/setup/setup_v0.$SETUP_VER.sh

WORKDIR /
RUN mkdir /ignition
WORKDIR /ignition
EXPOSE $IG_BASE_PORT
RUN echo "sh /ig_setup/setup_v0.$SETUP_VER.sh" >> /ig_setup/setup.sh
RUN sh /ig_setup/setup_v0.$SETUP_VER.sh

ENV PORT_LISTEN=9000

WORKDIR /ignition/ignition/
CMD python igchild2.py $PORT_LISTEN
